apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: nightly-prod-
# resources:
#   - ../../../../Jobs/rebuild
configMapGenerator:
  - name: payload
    files:
      - payload.yaml
    options:
      disableNameSuffixHash: true
