apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qe-trigger
  namespace: fbc-payload
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: fbc-payload
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          as: github-clone
          config:
            checkout:
              - fromFreight: true
                fromOrigin:
                  kind: Warehouse
                  name: fbc-payload
                path: ./github
            repoURL: https://github.com/openshift-cnv/cnv-fbc-payloads
        - uses: git-clone
          as: gitlab-clone
          config:
            checkout:
              - branch: main
                path: ./gitlab
            insecureSkipTLSVerify: true
            repoURL: https://gitlab.cee.redhat.com/openshift-virtualization/fbc-payloads
        - uses: copy
          as: payload-copy
          config:
            inPath: ./github
            outPath: ./gitlab
        - uses: git-commit
          as: gitlab-commit
          config:
            message: Update payload
            path: ./gitlab
        - uses: git-push
          as: gitlab-push
          config:
            path: ./gitlab
            targetBranch: main