apiVersion: batch/v1
kind: Job
metadata:
  # Must have a real name (Kustomize requires metadata.name).
  name: rebuild-fbc
  # Argo CD annotations for PostSync Job that gets removed before each sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/wave: "2"
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: payload
        configMap:
          name: payload
      containers:
      - name: rebuild
        image: quay.io/redhat-user-workloads/ocp-virt-images-tenant/pipeline-tools
        envFrom:
        - configMapRef:
            name: next-channel
        workingDir: /tmp
        volumeMounts:
        - name: payload
          mountPath: /tmp
        args:
        - /bin/sh
        - '-c'
        - |
          set -eux

          # Extract values from payload.yaml using yq
          HCO_BUNDLE_VERSION="$(yq '.hco_bundle_version' payload.yaml)"

          # Debug output for extracted values
          echo "HCO_BUNDLE_VERSION ---> ${HCO_BUNDLE_VERSION}"
          echo "NEXT_CHANNEL ---> ${NEXT_CHANNEL}"

          # Correctly construct the JSON payload for the curl request
          curl -s -X POST \
            "http://trigger-job.cnv-fbc-konflux:3000/api/trigger" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{
              \"build\": \"${HCO_BUNDLE_VERSION}\",
              \"channel\": \"${NEXT_CHANNEL}\",
              \"dryRun\": true
            }"

      restartPolicy: Never
