apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - releaseJob.yaml

configMapGenerator:
  - literals:
      - NAMESPACE="cnv-fbc-tenant"
      - DRY_RUN="true"
      - NOTIFICATION_URL=http://notification-service.cnv-fbc-konflux:3000/notifications/register
    name: release-config
    options:
      disableNameSuffixHash: true
  - name: release-files
    files:
      - manifest.yaml
    options:
      disableNameSuffixHash: true
images:
- name: quay.io/redhat-user-workloads/ocp-virt-images-tenant/pipeline-tools
  newTag: 909f4e68e74a3b8d98cbcff27219259d5b57eb57