apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.cee.redhat.com/openshift-virtualization/fbc-payloads/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && ( "v4-smokePoc/lanes/nightly/smoke/***".pathChanged() || ".tekton/v4-smokepoc-pull-request.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cnv-smoke-tests
    appstudio.openshift.io/component: v4-smokepoc
    pipelines.appstudio.openshift.io/type: build
  name: v4-smokepoc-on-pull-request
  namespace: cnv-qe-devops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cnv-qe-devops-tenant/v4-smokepoc:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: v4-smokePoc/lanes/nightly/smoke
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://gitlab.cee.redhat.com/openshift-virtualization/konflux-shared-pipelines.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/build-container/pipeline.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-v4-smokepoc
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
