apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-cnv/cnv-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "main" && ("v4.17/*".pathChanged() || ".tekton/v417-cnv-fbc-push.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cnv-fbc-v4-17
    appstudio.openshift.io/component: v417-cnv-fbc
    pipelines.appstudio.openshift.io/type: build
  name: v417-cnv-fbc-on-push
  namespace: cnv-fbc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cnv-fbc-tenant/cnv-fbc-v4-17/v417-cnv-fbc:{{revision}}
  - name: dockerfile
    value: catalog.Dockerfile
  - name: path-context
    value: v4.17
  pipelineRef:
    name: fbc-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
