apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-cnv/cnv-fbc-payloads-new?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" &&
      (target_branch == "main" || target_branch.startsWith("dev/")) &&
      ("v4-99/lanes/dev-preview/qe/payload.yaml".pathChanged() || ".tekton/verify-cnv-4-99-z-build-push.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cnv-smoke-tests
    appstudio.openshift.io/component: verify-cnv-4-99-z-build
    pipelines.appstudio.openshift.io/type: build
  name: verify-cnv-4-99-z-build-on-push
  namespace: cnv-qe-devops-tenant
spec:
  timeouts:
    pipeline: "6h0m0s"  # Overall timeout for the PipelineRun
    tasks: "5h0m0s"     # Cumulative timeout for non-finally tasks
    finally: "1h0m0s"   # Cumulative timeout for finally tasks
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cnv-qe-devops-tenant/verify-cnv-4-99-z-build:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: v4-99/lanes/dev-preview/qe
  - name: openshift-virtualization-test-image
    value: quay.io/openshift-cnv/openshift-virtualization-tests:latest
  - name: cnv-version
    value: "4.99"
  - name: prow-job
    value: periodic-ci-RedHatQE-interop-testing-master-cnv-odf-ocp4.20-konflux-cnv-odf-smoke-tests-aws-ipi-ocp420
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/openshift-cnv/tekton-tasks.git"
      - name: revision
        value: wip/smoke
      - name: pathInRepo
        value: "pipelines/run-cnv-smoke-tests/pipeline.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-verify-cnv-4-99-z-build
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
